/* istanbul ignore file */

export const REFRESH_LOCATION = 'REFRESH_LOCATION';
export const REFRESH_LOCATION_ERROR = 'REFRESH_LOCATION_ERROR';

export const FETCH_FORECAST_IN_PROGRESS = 'FETCH_FORECAST_IN_PROGRESS';
export const FETCH_FORECAST_SUCCESS = 'FETCH_FORECAST_SUCCESS';
export const FETCH_FORECAST_FAILURE = 'FETCH_FORECAST_FAILURE';
